[package]
name = "theory-graph-homework"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
eframe = "0.33.3"
egui = "0.33.3"
rfd = "0.16.0"
